site_name: cdflow2
site_url: https://developer.acuris.com/opensource/cdflow2/
repo_url: https://github.com/mergermarket/cdflow2/
copyright: © 2020 Mergermarket Limited. All rights reserved.
theme:
    name: material
    palette:
        primary: 'blue grey'
        accent: 'deep orange'
    logo: logo.svg